openapi: 3.0.0
info:
  title: Your API Name
  description: This is the API documentation for your application.
  version: 0.7.0
servers:
  - url: http://localhost:8000
    description: Local Development Server

paths:
  /users/signup:
    post:
      summary: ユーザの新規登録
      description: ユーザを新規登録する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: test@example.com
      responses:
        '201':
          description: ユーザの新規登録が成功した場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: AbCdE12345
                  email:
                    type: string
                    example: test@example.com
        '400':
          description: ユーザの新規登録が失敗した場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ユーザの新規登録に失敗しました
  /users/signin:
    post:
      summary: ユーザのログイン
      description: ユーザでログインする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: test@example.com
                password:
                  type: string
                  example: password
      responses:
        '200':
          description: ユーザのログインが成功した場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: AbCdEfG1234567
        '400':
          description: ユーザのログインが失敗した場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ユーザの新規登録に失敗しました
  /users/signout:
    post:
      summary: ユーザのログアウト
      description: ユーザがログアウトする
      responses:
        '200':
          description: ログアウトが成功した場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ログアウトしました
